//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.510
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.510.
// 
namespace mdlWebServiceEnviaDados.wbsvSiscoTratamentoErros {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wbsvSiscoTratamentoErrosSoap", Namespace="http://tempuri.org/")]
    public class wbsvSiscoTratamentoErros : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public wbsvSiscoTratamentoErros() {
            this.Url = "http://localhost/wbsvSiscoTratamentoErros/wbsvSiscoTratamentoErros.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/nRetornaColecaoIdErros", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] nRetornaColecaoIdErros(string strKey) {
            object[] results = this.Invoke("nRetornaColecaoIdErros", new object[] {
                        strKey});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginnRetornaColecaoIdErros(string strKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("nRetornaColecaoIdErros", new object[] {
                        strKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public int[] EndnRetornaColecaoIdErros(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/vErro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("dtOcorrencia")]
        public System.DateTime vErro(string strKey, int nIdErro, out string strNomeMaquina, out int nIdUsuario, out string strUsuario, out string strVersaoServidor, out string strVersaoCliente, out string mstrExceptionSource, out string mstrExceptionMessage, out string mstrExceptionStackTrace, out string mstrExceptionTargetSite, out string mstrExceptionHelpLink, out string mstrExceptionString) {
            object[] results = this.Invoke("vErro", new object[] {
                        strKey,
                        nIdErro});
            strNomeMaquina = ((string)(results[1]));
            nIdUsuario = ((int)(results[2]));
            strUsuario = ((string)(results[3]));
            strVersaoServidor = ((string)(results[4]));
            strVersaoCliente = ((string)(results[5]));
            mstrExceptionSource = ((string)(results[6]));
            mstrExceptionMessage = ((string)(results[7]));
            mstrExceptionStackTrace = ((string)(results[8]));
            mstrExceptionTargetSite = ((string)(results[9]));
            mstrExceptionHelpLink = ((string)(results[10]));
            mstrExceptionString = ((string)(results[11]));
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginvErro(string strKey, int nIdErro, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("vErro", new object[] {
                        strKey,
                        nIdErro}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.DateTime EndvErro(System.IAsyncResult asyncResult, out string strNomeMaquina, out int nIdUsuario, out string strUsuario, out string strVersaoServidor, out string strVersaoCliente, out string mstrExceptionSource, out string mstrExceptionMessage, out string mstrExceptionStackTrace, out string mstrExceptionTargetSite, out string mstrExceptionHelpLink, out string mstrExceptionString) {
            object[] results = this.EndInvoke(asyncResult);
            strNomeMaquina = ((string)(results[1]));
            nIdUsuario = ((int)(results[2]));
            strUsuario = ((string)(results[3]));
            strVersaoServidor = ((string)(results[4]));
            strVersaoCliente = ((string)(results[5]));
            mstrExceptionSource = ((string)(results[6]));
            mstrExceptionMessage = ((string)(results[7]));
            mstrExceptionStackTrace = ((string)(results[8]));
            mstrExceptionTargetSite = ((string)(results[9]));
            mstrExceptionHelpLink = ((string)(results[10]));
            mstrExceptionString = ((string)(results[11]));
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/bInsereErro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool bInsereErro(string strCodigoCliente, System.DateTime dtOcorrencia, string strNomeMaquina, int nIdUsuario, string strUsuario, string strVersaoServidor, string strVersaoCliente, string mstrExceptionSource, string mstrExceptionMessage, string mstrExceptionStackTrace, string mstrExceptionTargetSite, string mstrExceptionHelpLink, string mstrExceptionString) {
            object[] results = this.Invoke("bInsereErro", new object[] {
                        strCodigoCliente,
                        dtOcorrencia,
                        strNomeMaquina,
                        nIdUsuario,
                        strUsuario,
                        strVersaoServidor,
                        strVersaoCliente,
                        mstrExceptionSource,
                        mstrExceptionMessage,
                        mstrExceptionStackTrace,
                        mstrExceptionTargetSite,
                        mstrExceptionHelpLink,
                        mstrExceptionString});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginbInsereErro(string strCodigoCliente, System.DateTime dtOcorrencia, string strNomeMaquina, int nIdUsuario, string strUsuario, string strVersaoServidor, string strVersaoCliente, string mstrExceptionSource, string mstrExceptionMessage, string mstrExceptionStackTrace, string mstrExceptionTargetSite, string mstrExceptionHelpLink, string mstrExceptionString, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("bInsereErro", new object[] {
                        strCodigoCliente,
                        dtOcorrencia,
                        strNomeMaquina,
                        nIdUsuario,
                        strUsuario,
                        strVersaoServidor,
                        strVersaoCliente,
                        mstrExceptionSource,
                        mstrExceptionMessage,
                        mstrExceptionStackTrace,
                        mstrExceptionTargetSite,
                        mstrExceptionHelpLink,
                        mstrExceptionString}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndbInsereErro(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/vRemoveErros", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void vRemoveErros(string strKey, int nIdErro) {
            this.Invoke("vRemoveErros", new object[] {
                        strKey,
                        nIdErro});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginvRemoveErros(string strKey, int nIdErro, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("vRemoveErros", new object[] {
                        strKey,
                        nIdErro}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndvRemoveErros(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/bRemoveErros", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool bRemoveErros(string strKey) {
            object[] results = this.Invoke("bRemoveErros", new object[] {
                        strKey});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginbRemoveErros(string strKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("bRemoveErros", new object[] {
                        strKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndbRemoveErros(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
    }
}
