//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace mdlDataBaseAccess.Tabelas {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("XsdTbRomaneios")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class XsdTbRomaneios : global::System.Data.DataSet {
        
        private tbRomaneiosDataTable tabletbRomaneios;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public XsdTbRomaneios() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected XsdTbRomaneios(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["tbRomaneios"] != null)) {
                    base.Tables.Add(new tbRomaneiosDataTable(ds.Tables["tbRomaneios"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public tbRomaneiosDataTable tbRomaneios {
            get {
                return this.tabletbRomaneios;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            XsdTbRomaneios cln = ((XsdTbRomaneios)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["tbRomaneios"] != null)) {
                    base.Tables.Add(new tbRomaneiosDataTable(ds.Tables["tbRomaneios"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tabletbRomaneios = ((tbRomaneiosDataTable)(base.Tables["tbRomaneios"]));
            if ((initTable == true)) {
                if ((this.tabletbRomaneios != null)) {
                    this.tabletbRomaneios.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void InitClass() {
            this.DataSetName = "XsdTbRomaneios";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/XsdTbRomaneios.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tabletbRomaneios = new tbRomaneiosDataTable();
            base.Tables.Add(this.tabletbRomaneios);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private bool ShouldSerializetbRomaneios() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            XsdTbRomaneios ds = new XsdTbRomaneios();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public delegate void tbRomaneiosRowChangeEventHandler(object sender, tbRomaneiosRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class tbRomaneiosDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnidExportador;
            
            private global::System.Data.DataColumn columnidPE;
            
            private global::System.Data.DataColumn columnidRelatorio;
            
            private global::System.Data.DataColumn columndtDataEmissao;
            
            private global::System.Data.DataColumn columnnIdIdioma;
            
            private global::System.Data.DataColumn columnstrObservacao;
            
            private global::System.Data.DataColumn columnmstrObservacao;
            
            private global::System.Data.DataColumn columnstrNumero;
            
            private global::System.Data.DataColumn columnstrTotalVolumes;
            
            private global::System.Data.DataColumn columnnIdAssinatura;
            
            private global::System.Data.DataColumn columnnTipoOrdenacao;
            
            private global::System.Data.DataColumn columnbMostrarEmbalagensConsecutivas;
            
            private global::System.Data.DataColumn columnbMostrarVolumesConsecutivos;
            
            private global::System.Data.DataColumn columnnImpressoes;
            
            private global::System.Data.DataColumn columnbMostrarTotalVolumes;
            
            private global::System.Data.DataColumn columnstrFormatoDataEmissao;
            
            private global::System.Data.DataColumn columnnUnidadeMassaPesoLiquido;
            
            private global::System.Data.DataColumn columnnUnidadeMassaPesoBruto;
            
            private global::System.Data.DataColumn columnbEmbalagensIntermediarias;
            
            private global::System.Data.DataColumn columnbOtimizarEspaco;
            
            private global::System.Data.DataColumn columnbReplicarInformacoesVolumes;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public tbRomaneiosDataTable() {
                this.TableName = "tbRomaneios";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal tbRomaneiosDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected tbRomaneiosDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn idExportadorColumn {
                get {
                    return this.columnidExportador;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn idPEColumn {
                get {
                    return this.columnidPE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn idRelatorioColumn {
                get {
                    return this.columnidRelatorio;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn dtDataEmissaoColumn {
                get {
                    return this.columndtDataEmissao;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn nIdIdiomaColumn {
                get {
                    return this.columnnIdIdioma;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn strObservacaoColumn {
                get {
                    return this.columnstrObservacao;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn mstrObservacaoColumn {
                get {
                    return this.columnmstrObservacao;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn strNumeroColumn {
                get {
                    return this.columnstrNumero;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn strTotalVolumesColumn {
                get {
                    return this.columnstrTotalVolumes;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn nIdAssinaturaColumn {
                get {
                    return this.columnnIdAssinatura;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn nTipoOrdenacaoColumn {
                get {
                    return this.columnnTipoOrdenacao;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn bMostrarEmbalagensConsecutivasColumn {
                get {
                    return this.columnbMostrarEmbalagensConsecutivas;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn bMostrarVolumesConsecutivosColumn {
                get {
                    return this.columnbMostrarVolumesConsecutivos;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn nImpressoesColumn {
                get {
                    return this.columnnImpressoes;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn bMostrarTotalVolumesColumn {
                get {
                    return this.columnbMostrarTotalVolumes;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn strFormatoDataEmissaoColumn {
                get {
                    return this.columnstrFormatoDataEmissao;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn nUnidadeMassaPesoLiquidoColumn {
                get {
                    return this.columnnUnidadeMassaPesoLiquido;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn nUnidadeMassaPesoBrutoColumn {
                get {
                    return this.columnnUnidadeMassaPesoBruto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn bEmbalagensIntermediariasColumn {
                get {
                    return this.columnbEmbalagensIntermediarias;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn bOtimizarEspacoColumn {
                get {
                    return this.columnbOtimizarEspaco;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn bReplicarInformacoesVolumesColumn {
                get {
                    return this.columnbReplicarInformacoesVolumes;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public tbRomaneiosRow this[int index] {
                get {
                    return ((tbRomaneiosRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event tbRomaneiosRowChangeEventHandler tbRomaneiosRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event tbRomaneiosRowChangeEventHandler tbRomaneiosRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event tbRomaneiosRowChangeEventHandler tbRomaneiosRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event tbRomaneiosRowChangeEventHandler tbRomaneiosRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void AddtbRomaneiosRow(tbRomaneiosRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public tbRomaneiosRow AddtbRomaneiosRow(
                        int idExportador, 
                        string idPE, 
                        int idRelatorio, 
                        System.DateTime dtDataEmissao, 
                        int nIdIdioma, 
                        string strObservacao, 
                        string mstrObservacao, 
                        string strNumero, 
                        string strTotalVolumes, 
                        int nIdAssinatura, 
                        int nTipoOrdenacao, 
                        bool bMostrarEmbalagensConsecutivas, 
                        bool bMostrarVolumesConsecutivos, 
                        int nImpressoes, 
                        bool bMostrarTotalVolumes, 
                        string strFormatoDataEmissao, 
                        int nUnidadeMassaPesoLiquido, 
                        int nUnidadeMassaPesoBruto, 
                        bool bEmbalagensIntermediarias, 
                        bool bOtimizarEspaco, 
                        bool bReplicarInformacoesVolumes) {
                tbRomaneiosRow rowtbRomaneiosRow = ((tbRomaneiosRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        idExportador,
                        idPE,
                        idRelatorio,
                        dtDataEmissao,
                        nIdIdioma,
                        strObservacao,
                        mstrObservacao,
                        strNumero,
                        strTotalVolumes,
                        nIdAssinatura,
                        nTipoOrdenacao,
                        bMostrarEmbalagensConsecutivas,
                        bMostrarVolumesConsecutivos,
                        nImpressoes,
                        bMostrarTotalVolumes,
                        strFormatoDataEmissao,
                        nUnidadeMassaPesoLiquido,
                        nUnidadeMassaPesoBruto,
                        bEmbalagensIntermediarias,
                        bOtimizarEspaco,
                        bReplicarInformacoesVolumes};
                rowtbRomaneiosRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowtbRomaneiosRow);
                return rowtbRomaneiosRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public tbRomaneiosRow FindByidExportadoridPE(int idExportador, string idPE) {
                return ((tbRomaneiosRow)(this.Rows.Find(new object[] {
                            idExportador,
                            idPE})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                tbRomaneiosDataTable cln = ((tbRomaneiosDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new tbRomaneiosDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal void InitVars() {
                this.columnidExportador = base.Columns["idExportador"];
                this.columnidPE = base.Columns["idPE"];
                this.columnidRelatorio = base.Columns["idRelatorio"];
                this.columndtDataEmissao = base.Columns["dtDataEmissao"];
                this.columnnIdIdioma = base.Columns["nIdIdioma"];
                this.columnstrObservacao = base.Columns["strObservacao"];
                this.columnmstrObservacao = base.Columns["mstrObservacao"];
                this.columnstrNumero = base.Columns["strNumero"];
                this.columnstrTotalVolumes = base.Columns["strTotalVolumes"];
                this.columnnIdAssinatura = base.Columns["nIdAssinatura"];
                this.columnnTipoOrdenacao = base.Columns["nTipoOrdenacao"];
                this.columnbMostrarEmbalagensConsecutivas = base.Columns["bMostrarEmbalagensConsecutivas"];
                this.columnbMostrarVolumesConsecutivos = base.Columns["bMostrarVolumesConsecutivos"];
                this.columnnImpressoes = base.Columns["nImpressoes"];
                this.columnbMostrarTotalVolumes = base.Columns["bMostrarTotalVolumes"];
                this.columnstrFormatoDataEmissao = base.Columns["strFormatoDataEmissao"];
                this.columnnUnidadeMassaPesoLiquido = base.Columns["nUnidadeMassaPesoLiquido"];
                this.columnnUnidadeMassaPesoBruto = base.Columns["nUnidadeMassaPesoBruto"];
                this.columnbEmbalagensIntermediarias = base.Columns["bEmbalagensIntermediarias"];
                this.columnbOtimizarEspaco = base.Columns["bOtimizarEspaco"];
                this.columnbReplicarInformacoesVolumes = base.Columns["bReplicarInformacoesVolumes"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            private void InitClass() {
                this.columnidExportador = new global::System.Data.DataColumn("idExportador", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnidExportador);
                this.columnidPE = new global::System.Data.DataColumn("idPE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnidPE);
                this.columnidRelatorio = new global::System.Data.DataColumn("idRelatorio", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnidRelatorio);
                this.columndtDataEmissao = new global::System.Data.DataColumn("dtDataEmissao", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columndtDataEmissao);
                this.columnnIdIdioma = new global::System.Data.DataColumn("nIdIdioma", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnIdIdioma);
                this.columnstrObservacao = new global::System.Data.DataColumn("strObservacao", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnstrObservacao);
                this.columnmstrObservacao = new global::System.Data.DataColumn("mstrObservacao", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnmstrObservacao);
                this.columnstrNumero = new global::System.Data.DataColumn("strNumero", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnstrNumero);
                this.columnstrTotalVolumes = new global::System.Data.DataColumn("strTotalVolumes", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnstrTotalVolumes);
                this.columnnIdAssinatura = new global::System.Data.DataColumn("nIdAssinatura", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnIdAssinatura);
                this.columnnTipoOrdenacao = new global::System.Data.DataColumn("nTipoOrdenacao", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnTipoOrdenacao);
                this.columnbMostrarEmbalagensConsecutivas = new global::System.Data.DataColumn("bMostrarEmbalagensConsecutivas", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbMostrarEmbalagensConsecutivas);
                this.columnbMostrarVolumesConsecutivos = new global::System.Data.DataColumn("bMostrarVolumesConsecutivos", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbMostrarVolumesConsecutivos);
                this.columnnImpressoes = new global::System.Data.DataColumn("nImpressoes", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnImpressoes);
                this.columnbMostrarTotalVolumes = new global::System.Data.DataColumn("bMostrarTotalVolumes", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbMostrarTotalVolumes);
                this.columnstrFormatoDataEmissao = new global::System.Data.DataColumn("strFormatoDataEmissao", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnstrFormatoDataEmissao);
                this.columnnUnidadeMassaPesoLiquido = new global::System.Data.DataColumn("nUnidadeMassaPesoLiquido", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnUnidadeMassaPesoLiquido);
                this.columnnUnidadeMassaPesoBruto = new global::System.Data.DataColumn("nUnidadeMassaPesoBruto", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnnUnidadeMassaPesoBruto);
                this.columnbEmbalagensIntermediarias = new global::System.Data.DataColumn("bEmbalagensIntermediarias", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbEmbalagensIntermediarias);
                this.columnbOtimizarEspaco = new global::System.Data.DataColumn("bOtimizarEspaco", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbOtimizarEspaco);
                this.columnbReplicarInformacoesVolumes = new global::System.Data.DataColumn("bReplicarInformacoesVolumes", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnbReplicarInformacoesVolumes);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("XsdTbRomaneiosKey1", new global::System.Data.DataColumn[] {
                                this.columnidExportador,
                                this.columnidPE}, true));
                this.columnidExportador.AllowDBNull = false;
                this.columnidPE.AllowDBNull = false;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public tbRomaneiosRow NewtbRomaneiosRow() {
                return ((tbRomaneiosRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new tbRomaneiosRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(tbRomaneiosRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.tbRomaneiosRowChanged != null)) {
                    this.tbRomaneiosRowChanged(this, new tbRomaneiosRowChangeEvent(((tbRomaneiosRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.tbRomaneiosRowChanging != null)) {
                    this.tbRomaneiosRowChanging(this, new tbRomaneiosRowChangeEvent(((tbRomaneiosRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.tbRomaneiosRowDeleted != null)) {
                    this.tbRomaneiosRowDeleted(this, new tbRomaneiosRowChangeEvent(((tbRomaneiosRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.tbRomaneiosRowDeleting != null)) {
                    this.tbRomaneiosRowDeleting(this, new tbRomaneiosRowChangeEvent(((tbRomaneiosRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void RemovetbRomaneiosRow(tbRomaneiosRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                XsdTbRomaneios ds = new XsdTbRomaneios();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "tbRomaneiosDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class tbRomaneiosRow : global::System.Data.DataRow {
            
            private tbRomaneiosDataTable tabletbRomaneios;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal tbRomaneiosRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tabletbRomaneios = ((tbRomaneiosDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public int idExportador {
                get {
                    return ((int)(this[this.tabletbRomaneios.idExportadorColumn]));
                }
                set {
                    this[this.tabletbRomaneios.idExportadorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string idPE {
                get {
                    return ((string)(this[this.tabletbRomaneios.idPEColumn]));
                }
                set {
                    this[this.tabletbRomaneios.idPEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public int idRelatorio {
                get {
                    try {
                        return ((int)(this[this.tabletbRomaneios.idRelatorioColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'idRelatorio\' in table \'tbRomaneios\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletbRomaneios.idRelatorioColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public System.DateTime dtDataEmissao {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tabletbRomaneios.dtDataEmissaoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'dtDataEmissao\' in table \'tbRomaneios\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletbRomaneios.dtDataEmissaoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public int nIdIdioma {
                get {
                    try {
                        return ((int)(this[this.tabletbRomaneios.nIdIdiomaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nIdIdioma\' in table \'tbRomaneios\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletbRomaneios.nIdIdiomaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string strObservacao {
                get {
                    try {
                        return ((string)(this[this.tabletbRomaneios.strObservacaoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'strObservacao\' in table \'tbRomaneios\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletbRomaneios.strObservacaoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string mstrObservacao {
                get {
                    try {
                        return ((string)(this[this.tabletbRomaneios.mstrObservacaoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'mstrObservacao\' in table \'tbRomaneios\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletbRomaneios.mstrObservacaoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string strNumero {
                get {
                    try {
                        return ((string)(this[this.tabletbRomaneios.strNumeroColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'strNumero\' in table \'tbRomaneios\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletbRomaneios.strNumeroColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string strTotalVolumes {
                get {
                    try {
                        return ((string)(this[this.tabletbRomaneios.strTotalVolumesColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'strTotalVolumes\' in table \'tbRomaneios\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletbRomaneios.strTotalVolumesColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public int nIdAssinatura {
                get {
                    try {
                        return ((int)(this[this.tabletbRomaneios.nIdAssinaturaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nIdAssinatura\' in table \'tbRomaneios\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletbRomaneios.nIdAssinaturaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public int nTipoOrdenacao {
                get {
                    try {
                        return ((int)(this[this.tabletbRomaneios.nTipoOrdenacaoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nTipoOrdenacao\' in table \'tbRomaneios\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletbRomaneios.nTipoOrdenacaoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool bMostrarEmbalagensConsecutivas {
                get {
                    try {
                        return ((bool)(this[this.tabletbRomaneios.bMostrarEmbalagensConsecutivasColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'bMostrarEmbalagensConsecutivas\' in table \'tbRomaneios\' is D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tabletbRomaneios.bMostrarEmbalagensConsecutivasColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool bMostrarVolumesConsecutivos {
                get {
                    try {
                        return ((bool)(this[this.tabletbRomaneios.bMostrarVolumesConsecutivosColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'bMostrarVolumesConsecutivos\' in table \'tbRomaneios\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tabletbRomaneios.bMostrarVolumesConsecutivosColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public int nImpressoes {
                get {
                    try {
                        return ((int)(this[this.tabletbRomaneios.nImpressoesColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nImpressoes\' in table \'tbRomaneios\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletbRomaneios.nImpressoesColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool bMostrarTotalVolumes {
                get {
                    try {
                        return ((bool)(this[this.tabletbRomaneios.bMostrarTotalVolumesColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'bMostrarTotalVolumes\' in table \'tbRomaneios\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletbRomaneios.bMostrarTotalVolumesColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string strFormatoDataEmissao {
                get {
                    try {
                        return ((string)(this[this.tabletbRomaneios.strFormatoDataEmissaoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'strFormatoDataEmissao\' in table \'tbRomaneios\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletbRomaneios.strFormatoDataEmissaoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public int nUnidadeMassaPesoLiquido {
                get {
                    try {
                        return ((int)(this[this.tabletbRomaneios.nUnidadeMassaPesoLiquidoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nUnidadeMassaPesoLiquido\' in table \'tbRomaneios\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tabletbRomaneios.nUnidadeMassaPesoLiquidoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public int nUnidadeMassaPesoBruto {
                get {
                    try {
                        return ((int)(this[this.tabletbRomaneios.nUnidadeMassaPesoBrutoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'nUnidadeMassaPesoBruto\' in table \'tbRomaneios\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletbRomaneios.nUnidadeMassaPesoBrutoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool bEmbalagensIntermediarias {
                get {
                    try {
                        return ((bool)(this[this.tabletbRomaneios.bEmbalagensIntermediariasColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'bEmbalagensIntermediarias\' in table \'tbRomaneios\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tabletbRomaneios.bEmbalagensIntermediariasColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool bOtimizarEspaco {
                get {
                    try {
                        return ((bool)(this[this.tabletbRomaneios.bOtimizarEspacoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'bOtimizarEspaco\' in table \'tbRomaneios\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletbRomaneios.bOtimizarEspacoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool bReplicarInformacoesVolumes {
                get {
                    try {
                        return ((bool)(this[this.tabletbRomaneios.bReplicarInformacoesVolumesColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'bReplicarInformacoesVolumes\' in table \'tbRomaneios\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tabletbRomaneios.bReplicarInformacoesVolumesColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsidRelatorioNull() {
                return this.IsNull(this.tabletbRomaneios.idRelatorioColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetidRelatorioNull() {
                this[this.tabletbRomaneios.idRelatorioColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsdtDataEmissaoNull() {
                return this.IsNull(this.tabletbRomaneios.dtDataEmissaoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetdtDataEmissaoNull() {
                this[this.tabletbRomaneios.dtDataEmissaoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsnIdIdiomaNull() {
                return this.IsNull(this.tabletbRomaneios.nIdIdiomaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetnIdIdiomaNull() {
                this[this.tabletbRomaneios.nIdIdiomaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsstrObservacaoNull() {
                return this.IsNull(this.tabletbRomaneios.strObservacaoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetstrObservacaoNull() {
                this[this.tabletbRomaneios.strObservacaoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsmstrObservacaoNull() {
                return this.IsNull(this.tabletbRomaneios.mstrObservacaoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetmstrObservacaoNull() {
                this[this.tabletbRomaneios.mstrObservacaoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsstrNumeroNull() {
                return this.IsNull(this.tabletbRomaneios.strNumeroColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetstrNumeroNull() {
                this[this.tabletbRomaneios.strNumeroColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsstrTotalVolumesNull() {
                return this.IsNull(this.tabletbRomaneios.strTotalVolumesColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetstrTotalVolumesNull() {
                this[this.tabletbRomaneios.strTotalVolumesColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsnIdAssinaturaNull() {
                return this.IsNull(this.tabletbRomaneios.nIdAssinaturaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetnIdAssinaturaNull() {
                this[this.tabletbRomaneios.nIdAssinaturaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsnTipoOrdenacaoNull() {
                return this.IsNull(this.tabletbRomaneios.nTipoOrdenacaoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetnTipoOrdenacaoNull() {
                this[this.tabletbRomaneios.nTipoOrdenacaoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsbMostrarEmbalagensConsecutivasNull() {
                return this.IsNull(this.tabletbRomaneios.bMostrarEmbalagensConsecutivasColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetbMostrarEmbalagensConsecutivasNull() {
                this[this.tabletbRomaneios.bMostrarEmbalagensConsecutivasColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsbMostrarVolumesConsecutivosNull() {
                return this.IsNull(this.tabletbRomaneios.bMostrarVolumesConsecutivosColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetbMostrarVolumesConsecutivosNull() {
                this[this.tabletbRomaneios.bMostrarVolumesConsecutivosColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsnImpressoesNull() {
                return this.IsNull(this.tabletbRomaneios.nImpressoesColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetnImpressoesNull() {
                this[this.tabletbRomaneios.nImpressoesColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsbMostrarTotalVolumesNull() {
                return this.IsNull(this.tabletbRomaneios.bMostrarTotalVolumesColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetbMostrarTotalVolumesNull() {
                this[this.tabletbRomaneios.bMostrarTotalVolumesColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsstrFormatoDataEmissaoNull() {
                return this.IsNull(this.tabletbRomaneios.strFormatoDataEmissaoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetstrFormatoDataEmissaoNull() {
                this[this.tabletbRomaneios.strFormatoDataEmissaoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsnUnidadeMassaPesoLiquidoNull() {
                return this.IsNull(this.tabletbRomaneios.nUnidadeMassaPesoLiquidoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetnUnidadeMassaPesoLiquidoNull() {
                this[this.tabletbRomaneios.nUnidadeMassaPesoLiquidoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsnUnidadeMassaPesoBrutoNull() {
                return this.IsNull(this.tabletbRomaneios.nUnidadeMassaPesoBrutoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetnUnidadeMassaPesoBrutoNull() {
                this[this.tabletbRomaneios.nUnidadeMassaPesoBrutoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsbEmbalagensIntermediariasNull() {
                return this.IsNull(this.tabletbRomaneios.bEmbalagensIntermediariasColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetbEmbalagensIntermediariasNull() {
                this[this.tabletbRomaneios.bEmbalagensIntermediariasColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsbOtimizarEspacoNull() {
                return this.IsNull(this.tabletbRomaneios.bOtimizarEspacoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetbOtimizarEspacoNull() {
                this[this.tabletbRomaneios.bOtimizarEspacoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsbReplicarInformacoesVolumesNull() {
                return this.IsNull(this.tabletbRomaneios.bReplicarInformacoesVolumesColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetbReplicarInformacoesVolumesNull() {
                this[this.tabletbRomaneios.bReplicarInformacoesVolumesColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public class tbRomaneiosRowChangeEvent : global::System.EventArgs {
            
            private tbRomaneiosRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public tbRomaneiosRowChangeEvent(tbRomaneiosRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public tbRomaneiosRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591