//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.510
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace mdlDataBaseData.Tabelas {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class XsdTbStatisticReports : DataSet {
        
        private tbStatisticReportsDataTable tabletbStatisticReports;
        
        public XsdTbStatisticReports() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected XsdTbStatisticReports(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["tbStatisticReports"] != null)) {
                    this.Tables.Add(new tbStatisticReportsDataTable(ds.Tables["tbStatisticReports"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public tbStatisticReportsDataTable tbStatisticReports {
            get {
                return this.tabletbStatisticReports;
            }
        }
        
        public override DataSet Clone() {
            XsdTbStatisticReports cln = ((XsdTbStatisticReports)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["tbStatisticReports"] != null)) {
                this.Tables.Add(new tbStatisticReportsDataTable(ds.Tables["tbStatisticReports"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tabletbStatisticReports = ((tbStatisticReportsDataTable)(this.Tables["tbStatisticReports"]));
            if ((this.tabletbStatisticReports != null)) {
                this.tabletbStatisticReports.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "XsdTbStatisticReports";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/XsdTbStatisticReports.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tabletbStatisticReports = new tbStatisticReportsDataTable();
            this.Tables.Add(this.tabletbStatisticReports);
        }
        
        private bool ShouldSerializetbStatisticReports() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void tbStatisticReportsRowChangeEventHandler(object sender, tbStatisticReportsRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tbStatisticReportsDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnnIdReport;
            
            private DataColumn columnstrName;
            
            private DataColumn columnmstrData;
            
            internal tbStatisticReportsDataTable() : 
                    base("tbStatisticReports") {
                this.InitClass();
            }
            
            internal tbStatisticReportsDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn nIdReportColumn {
                get {
                    return this.columnnIdReport;
                }
            }
            
            internal DataColumn strNameColumn {
                get {
                    return this.columnstrName;
                }
            }
            
            internal DataColumn mstrDataColumn {
                get {
                    return this.columnmstrData;
                }
            }
            
            public tbStatisticReportsRow this[int index] {
                get {
                    return ((tbStatisticReportsRow)(this.Rows[index]));
                }
            }
            
            public event tbStatisticReportsRowChangeEventHandler tbStatisticReportsRowChanged;
            
            public event tbStatisticReportsRowChangeEventHandler tbStatisticReportsRowChanging;
            
            public event tbStatisticReportsRowChangeEventHandler tbStatisticReportsRowDeleted;
            
            public event tbStatisticReportsRowChangeEventHandler tbStatisticReportsRowDeleting;
            
            public void AddtbStatisticReportsRow(tbStatisticReportsRow row) {
                this.Rows.Add(row);
            }
            
            public tbStatisticReportsRow AddtbStatisticReportsRow(int nIdReport, string strName, string mstrData) {
                tbStatisticReportsRow rowtbStatisticReportsRow = ((tbStatisticReportsRow)(this.NewRow()));
                rowtbStatisticReportsRow.ItemArray = new object[] {
                        nIdReport,
                        strName,
                        mstrData};
                this.Rows.Add(rowtbStatisticReportsRow);
                return rowtbStatisticReportsRow;
            }
            
            public tbStatisticReportsRow FindBynIdReport(int nIdReport) {
                return ((tbStatisticReportsRow)(this.Rows.Find(new object[] {
                            nIdReport})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                tbStatisticReportsDataTable cln = ((tbStatisticReportsDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new tbStatisticReportsDataTable();
            }
            
            internal void InitVars() {
                this.columnnIdReport = this.Columns["nIdReport"];
                this.columnstrName = this.Columns["strName"];
                this.columnmstrData = this.Columns["mstrData"];
            }
            
            private void InitClass() {
                this.columnnIdReport = new DataColumn("nIdReport", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnnIdReport);
                this.columnstrName = new DataColumn("strName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnstrName);
                this.columnmstrData = new DataColumn("mstrData", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnmstrData);
                this.Constraints.Add(new UniqueConstraint("XsdTbStatisticReportsKey1", new DataColumn[] {
                                this.columnnIdReport}, true));
                this.columnnIdReport.AllowDBNull = false;
                this.columnnIdReport.Unique = true;
            }
            
            public tbStatisticReportsRow NewtbStatisticReportsRow() {
                return ((tbStatisticReportsRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new tbStatisticReportsRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(tbStatisticReportsRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.tbStatisticReportsRowChanged != null)) {
                    this.tbStatisticReportsRowChanged(this, new tbStatisticReportsRowChangeEvent(((tbStatisticReportsRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.tbStatisticReportsRowChanging != null)) {
                    this.tbStatisticReportsRowChanging(this, new tbStatisticReportsRowChangeEvent(((tbStatisticReportsRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.tbStatisticReportsRowDeleted != null)) {
                    this.tbStatisticReportsRowDeleted(this, new tbStatisticReportsRowChangeEvent(((tbStatisticReportsRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.tbStatisticReportsRowDeleting != null)) {
                    this.tbStatisticReportsRowDeleting(this, new tbStatisticReportsRowChangeEvent(((tbStatisticReportsRow)(e.Row)), e.Action));
                }
            }
            
            public void RemovetbStatisticReportsRow(tbStatisticReportsRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tbStatisticReportsRow : DataRow {
            
            private tbStatisticReportsDataTable tabletbStatisticReports;
            
            internal tbStatisticReportsRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tabletbStatisticReports = ((tbStatisticReportsDataTable)(this.Table));
            }
            
            public int nIdReport {
                get {
                    return ((int)(this[this.tabletbStatisticReports.nIdReportColumn]));
                }
                set {
                    this[this.tabletbStatisticReports.nIdReportColumn] = value;
                }
            }
            
            public string strName {
                get {
                    try {
                        return ((string)(this[this.tabletbStatisticReports.strNameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletbStatisticReports.strNameColumn] = value;
                }
            }
            
            public string mstrData {
                get {
                    try {
                        return ((string)(this[this.tabletbStatisticReports.mstrDataColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletbStatisticReports.mstrDataColumn] = value;
                }
            }
            
            public bool IsstrNameNull() {
                return this.IsNull(this.tabletbStatisticReports.strNameColumn);
            }
            
            public void SetstrNameNull() {
                this[this.tabletbStatisticReports.strNameColumn] = System.Convert.DBNull;
            }
            
            public bool IsmstrDataNull() {
                return this.IsNull(this.tabletbStatisticReports.mstrDataColumn);
            }
            
            public void SetmstrDataNull() {
                this[this.tabletbStatisticReports.mstrDataColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tbStatisticReportsRowChangeEvent : EventArgs {
            
            private tbStatisticReportsRow eventRow;
            
            private DataRowAction eventAction;
            
            public tbStatisticReportsRowChangeEvent(tbStatisticReportsRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public tbStatisticReportsRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
